Task/upup 330
MobileUpLLC/Utils pull request #20
Opened 2022-09-28 08:08 UTC by vitaliiVishnyakov

https://mobileup.atlassian.net/browse/UPUP-330

2022-09-28 09:04 UTC, petrovichppp requested changes

2022-09-28 09:04 UTC, petrovichppp commented on Package.swift
> +        .iOS(.v13)
@vitaliiVishnyakov Зачем подняли версию iOS?

2022-09-28 11:52 UTC, vitaliiVishnyakov commented on Package.swift
> +        .iOS(.v13)
.instantiateViewController(identifier: storyboardId) доступен только с 13 версии. Плюс 13 минимальный таргет у нас в приложениях, поэтому не мне показалась что это хорошее решение  - повысить до 13

2022-09-28 12:06 UTC, vitaliiVishnyakov commented on Package.swift
> +        .iOS(.v13)
раньше использовали .instantiateViewControllerWithIdentifier(storyboardId)

2022-10-04 09:11 UTC, petrovichppp requested changes

2022-10-04 09:11 UTC, petrovichppp commented on Sources/Utils/Protocols/StoryboardInitable/StoryboardInitable.swift
> +//  File.swift
Что за File? Дадим корректное название

2022-10-04 09:11 UTC, petrovichppp commented on Sources/Utils/Protocols/StoryboardInitable/StoryboardInitable.swift
> +public protocol StoryboardInitable: Initable {
Почему мы создали отдельную папку StoryboardInitable, а не положили в папку Initable? Перенесем в Initable

2022-10-04 09:11 UTC, petrovichppp commented on Package.swift
> -        .iOS(.v12)
В следующий раз, если потребуется поднять версию, обсуждаем причину поднятия версии с тимлидом/техлидом. Если решили поднимать, то создается отдельный мр с поднятием версии

2022-10-04 09:11 UTC, petrovichppp commented on UtilsExample/Source/UI/ExampleViewController.swift
> +    @IBAction private func openStoryboardInitableControllerTap() {
Переименуем на openStoryboardInitableControllerButtonTapped

2022-10-04 09:11 UTC, petrovichppp commented on UtilsExample/UtilsExample.xcodeproj/project.pbxproj
> +		FAE0A9FD28E42CF500FB7EAD /* Storyboard */ = {
Закинули контроллер в папку с названием Storyboard и это некорректное название. Давай перенесем это в папку Controllers, где лежат другие контроллеры

2022-10-04 09:11 UTC, petrovichppp commented on UtilsExample/UtilsExample.xcodeproj/project.pbxproj
> +				minimumVersion = 0.0.32;
А это что за версия? Зачем поменяли?

2022-10-04 09:35 UTC, vitaliiVishnyakov commented on Package.swift
> -        .iOS(.v12)
Можно ли назвать тред шесть дней назад обсуждением? Или это объяснение постфактум ?

2022-10-04 09:51 UTC, vitaliiVishnyakov commented on UtilsExample/UtilsExample.xcodeproj/project.pbxproj
> +				minimumVersion = 0.0.32;
В исходники изменения вносим так: открывает Package.swift и делаем правки в этом проекте, это собственно изминения в нашей либе, далее мы пушима гит.
Заходим в гит и делаем пре-релиз с тегом, каждый раз увеличиваем номер тега. Потом выпускаем релиз.
Заходим в example проект и подтягиваем поеслдний релиз, так как там у нас изменеия. Подтягивание происходит за счёт изминения версии пакета в проджект файле, вписывает наш последний тэг.

2022-10-04 09:54 UTC, petrovichppp commented on Package.swift
> -        .iOS(.v12)
Тот тред, где мы это обсуждали я закрыл, так как причина ясна. Этот тред на будущее

2022-10-04 09:56 UTC, vitaliiVishnyakov commented on Package.swift
> -        .iOS(.v12)
А, понял

2022-10-06 12:34 UTC, petrovichppp commented on UtilsExample/UtilsExample.xcodeproj/project.pbxproj
> +/* Begin XCRemoteSwiftPackageReference section */
Думаю этого блока не должно быть теперь, @vitaliiVishnyakov что думаешь?

2022-10-06 12:47 UTC, petrovichppp approved these changes

2022-10-06 12:47 UTC, merged