Task/upup 355 multicast delegate
MobileUpLLC/Utils pull request #23
Opened 2022-10-07 14:37 UTC by vitaliiVishnyakov

https://mobileup.atlassian.net/browse/UPUP-355

2022-10-11 11:52 UTC, petrovichppp requested changes

2022-10-11 11:52 UTC, petrovichppp commented on Sources/Utils/Helpers/MulticastDelegate.swift
> +// таблица будет хранить слабую ссылку, пока не будут вызыванны методы add или remove или invokeForEachDelegate,
уберем запятую после invokeForEachDelegate

2022-10-11 11:52 UTC, petrovichppp commented on UtilsExample/Source/UI/ExampleViewController.swift
> +    @IBAction private func openMulticastDelegateExampleTapped() {
openMulticastDelegateExampleButtonTapped. По кнопке же нажимаем?

2022-10-11 11:52 UTC, petrovichppp commented on UtilsExample/Source/UI/Initable/Controllers/MulticastDelegateController/MulticastDelegateController.swift
> +class MulticastDelegateController: UIViewController, CodeInitable {
![image](https://user-images.githubusercontent.com/52822979/195079768-fce49885-14a0-453f-8998-e6e09a3c82d3.png)

У нас для каждого блока/функционала/возможности есть своя папочка. Давай сделаем тоже самое и для MulticastDelegate

2022-10-11 11:52 UTC, petrovichppp commented on UtilsExample/Source/UI/Initable/Controllers/MulticastDelegateController/MulticastDelegateController.swift
> +        let button = UIButton(type: .system)
А зачем нам эта кнопка?  по нажатию ничего не происходит. Давай будем removeDelegate делать во viewDidDisappear, а подписку во viewWillAppear

2022-10-11 11:52 UTC, petrovichppp commented on UtilsExample/Source/UI/Initable/Controllers/MulticastDelegateController/MulticastDelegateController.swift
> +        label.font = .systemFont(ofSize: Constants.fontSize)
Зачем нам нужен label? По названию непонятно зачем он нужен

2022-10-11 11:52 UTC, petrovichppp commented on UtilsExample/Source/UI/Initable/Controllers/MulticastDelegateController/MulticastDelegateController.swift
> +            [
А чего мы квадратные скобки на новую строку перенесли? Давай сделаем по аналогии с FormCodeView

2022-10-11 11:52 UTC, petrovichppp commented on UtilsExample/UtilsExampleTests/UtilsExampleTests.swift
> +
а на кой нам здесь пустая строка? не делаем так уже

2022-10-11 12:15 UTC, vitaliiVishnyakov commented on UtilsExample/Source/UI/Initable/Controllers/MulticastDelegateController/MulticastDelegateController.swift
> +        let button = UIButton(type: .system)
По нажатию на эту кнопку запускается invokeForEachDelegate и на экран выводится новое значение, нам же нужен пример, вот я и показываю что по нажатию на кнопку мы обновляем значение в accumulator и отображаем это в accumulatorLabel

2022-10-11 13:24 UTC, petrovichppp commented on UtilsExample/Source/UI/Initable/Controllers/MulticastDelegateController/MulticastDelegateController.swift
> +        let button = UIButton(type: .system)
У меня по нажатию на кнопку ничего не произошло

2022-10-11 14:30 UTC, petrovichppp commented on UtilsExample/Source/UI/Initable/Controllers/MulticastDelegateController/MulticastDelegateController.swift
> +        let button = UIButton(type: .system)
А что по этому? "Давай будем removeDelegate делать во viewDidDisappear, а подписку во viewWillAppear."

2022-10-12 05:04 UTC, petrovichppp requested changes

2022-10-12 05:04 UTC, petrovichppp commented on UtilsExample/Source/UI/MulticastDelegate/MulticastDelegateController.swift
> +    private func setupButton() {
переименуем на setupAccumulatorButton. Для лейбла аналогично

2022-10-12 05:04 UTC, petrovichppp commented on UtilsExample/Source/UI/MulticastDelegate/MulticastDelegateController.swift
> +    @objc private func showAccumulatorViewTapped() {
Переименуем на showAccumulatorButtonTapped

2022-11-03 09:53 UTC, petrovichppp commented on Sources/Utils/Helpers/MulticastDelegate.swift
> +    public func invokeForEachDelegate(_ handler: (T) -> Void) {
Нам нужно добавить метод, который будет подчищать массив врапперов, если delegate  враппера == nil. Соответсвенно вызывать его в методах add, remove, invokeForEachDelegate.

2022-11-07 11:10 UTC, petrovichppp commented on Sources/Utils/Helpers/MulticastDelegate.swift
> +    public var delegates: [T] { wrappers.compactMap { $0.delegate } as! [T] }
Здесь можем избавиться от force unwrap? 

Например так:

{ $0.delegate as? T } }

2022-11-07 11:24 UTC, vitaliiVishnyakov commented on Sources/Utils/Helpers/MulticastDelegate.swift
> +    public var delegates: [T] { wrappers.compactMap { $0.delegate } as! [T] }
можно

2022-11-07 11:33 UTC, petrovichppp approved these changes

2022-11-09 12:45 UTC, timonity requested changes

2022-11-09 12:45 UTC, timonity commented on Sources/Utils/Helpers/MulticastDelegate.swift
> +    private var wrappers: [Wrapper] = []
А почему это массив? Разве нам нужен здесь порядок?

2022-11-09 12:45 UTC, timonity commented on Sources/Utils/Helpers/MulticastDelegate.swift
> +open class MulticastDelegate<T> {
Предлагаю написать инструкцию в ридми, как им пользоваться

2022-11-09 12:45 UTC, timonity commented on UtilsExample/Source/UI/MulticastDelegate/MulticastDelegateController.swift
> +private protocol TestDelegate: AnyObject {
Предлагаю протокол и модели разместить выше объявления контроллера в этом файле

2022-11-09 12:45 UTC, timonity commented on UtilsExample/UtilsExampleTests/UtilsExampleTests.swift
> +    func testMulticastDelegateInvoke() {
1.Предлагаю унести это в отдельный файл MulticastDelegateTests.swift
2. Общий код для двух тесткейсов переиспользовать

2022-11-09 12:45 UTC, timonity commented on UtilsExample/UtilsExampleTests/MulticastDelegateTestClasses.swift
> +protocol Delegate: AnyObject {
Унесем протокол и классы в этом файле в файл с тесткейсами для MulticastDeledate

2022-11-09 12:45 UTC, timonity commented on Sources/Utils/Helpers/MulticastDelegate.swift
> +    public var delegates: [T] { wrappers.compactMap { $0.delegate as? T } }
Для чего эта пропертя публичная?

2022-11-09 12:45 UTC, timonity commented on Sources/Utils/Helpers/MulticastDelegate.swift
> +    private class Wrapper {
1. Предлагаю вынести этот класс выше объявления класса MulticastDelegate
2. Сделать класс приватным в рамках файла 
3. А почему это класс, а не структура?

2022-11-09 12:45 UTC, timonity commented on UtilsExample/Source/UI/MulticastDelegate/MulticastDelegateController.swift
> +    private let accumulatorLabel = UILabel()
Объявим тут через weak var

2022-11-09 12:45 UTC, timonity commented on UtilsExample/Source/UI/MulticastDelegate/MulticastDelegateController.swift
> +        multicastDelegate.remove(delegate: testFirstObject)
Зачем мы это делаем?

2022-11-09 15:46 UTC, vitaliiVishnyakov commented on UtilsExample/Source/UI/MulticastDelegate/MulticastDelegateController.swift
> +        multicastDelegate.remove(delegate: testFirstObject)
в качестве примера, но здесь он скорее путает

2022-11-09 15:49 UTC, vitaliiVishnyakov commented on UtilsExample/Source/UI/MulticastDelegate/MulticastDelegateController.swift
> +    private let accumulatorLabel = UILabel()
Оно же тогда сразу удалится, или я что-то не понимаю?

2022-11-09 15:53 UTC, vitaliiVishnyakov commented on Sources/Utils/Helpers/MulticastDelegate.swift
> +    private class Wrapper {
с классом удобнее реализовать hashable, а если будет struct, то тоже будет храниться на куче из-за weak var delegate: AnyObject?

2022-11-10 07:49 UTC, timonity commented on UtilsExample/Source/UI/MulticastDelegate/MulticastDelegateController.swift
> +    private let accumulatorLabel = UILabel()
Посмотри шаблон контроллера в разделе нашего код стиля. Предлагаю сделать контроллер по этому шаблону

2022-11-10 08:05 UTC, timonity requested changes

2022-11-10 08:05 UTC, timonity commented on README.md
> +1. Use ```func add(delegate: T)``` for add delegate
1. Добавим в пример то, как он объявляется 
```swift
protocol FooDelegate: AnyObject { 

    func bar()
 }

let multicastDelegate = MulticastDelegate<FooDelegate>()
```
2. Не нужно в инструкции дублировать объявления методов. Вызова с описанием того, что делает вызов, будет достаточно

2022-11-10 08:05 UTC, timonity commented on README.md
> +            accumulator = delegate.test(accumulator: accumulator)
Аккумулятор сбивает с толку. Предлагаю сделать попроще
```swift
multicastDelegate.invokeForEachDelegate { delegate in
  delegate.bar()
}
```

2022-11-10 08:05 UTC, timonity commented on Sources/Utils/Helpers/MulticastDelegate.swift
> +    public init() { }
Нам действительно нужно так публично делать инит?

2022-11-10 09:38 UTC, vitaliiVishnyakov commented on README.md
> +            accumulator = delegate.test(accumulator: accumulator)
тогда же получается бессмысленно делать controller под пример multicastDelegate?

2022-11-10 09:39 UTC, vitaliiVishnyakov commented on Sources/Utils/Helpers/MulticastDelegate.swift
> +    public init() { }
да

2022-11-10 14:03 UTC, timonity commented on README.md
> +            accumulator = delegate.test(accumulator: accumulator)
Нет, для примера вполне норм. Но инструкция должна быть максимально прозрачной и бустроусваиваемой

2022-11-10 14:05 UTC, timonity approved these changes

2022-11-10 14:05 UTC, timonity commented on UtilsExample/Source/UI/MulticastDelegate/MulticastDelegateController.swift
> +        return label
В таких случаях желательно return отделить пустой строкой

2022-11-10 16:58 UTC, merged