remove serverClient
MobileUpLLC/Utils pull request #41
Opened 2023-04-04 12:30 UTC by vitaliiVishnyakov

2023-04-04 12:30 UTC, vitaliiVishnyakov commented
https://ascnt.atlassian.net/browse/UPUP-509

2023-04-05 06:16 UTC, timonity requested changes

2023-04-05 06:16 UTC, timonity commented on README.md
>  - iOS 12.0 +
Заменим здесь на iOS 13.0 +

2023-04-05 06:16 UTC, timonity commented on Package.swift
>      ],
1. Поднимем версию до 0.1.0 для кокоаподс и для SPM.
2. Укажем это в ридми файле

2023-04-13 05:56 UTC, timonity approved these changes

2023-04-14 08:28 UTC, merged